### ISSUE TITLE
Upstream to nixpkgs?

### ISSUE THREAD

**Issue by kevincox** [mmai/funkwhale-nixos#2]
Hi, would you be interested in merging this upstream? I can help out with the process if you are interested.

**Comment by mmai** [comment]
Hi Kevin, I tried to but I finally gave up not being able to conform to the structure desired by the NixOS maintainers.
It was more than a year ago, maybe it's easier to package a Django app now, but  I don't have the time to work on it right now. 
The pull request is here if you want to take a look : https://github.com/NixOS/nixpkgs/pull/53416

**Comment by kevincox** [comment]
Thanks for the links. I'll see if I can piece it together.
